### PR TITLE
Middy as peer dep

### PR DESCRIPTION
**Pull request by russell-dot-js**

### CODE REVIEW

**Comment by kernwig** [comment]
Let me contemplate. This is probably the correct thing to do, but it would require a major version number bump because it is not backward compatible.

**Comment by kernwig** [comment]
Middy has a history of making incompatible version changes on minor version numbers. (As you can see in #17 when upgrading from 0.19 to 0.29.) Setting the peerDependency to "0.x.x" faces a high probability of breakage in the future.

Locking to the specific compatible version (as it was previously "0.19.1", not "^0.19.1") seems the only way to avoid downstream changes to Middy from breaking Sailplane. Should they adopt semver in the future, we can then then switch to peerDependency.

Does this make sense, or do you see a flaw in my thinking?

(If you agree, then this PR would be dropped and in #17, the dependency would change to "0.29.x".)

**Comment by russell-dot-js** [comment]
In my experience middy hasn't made a lot of incompatible changes (except with their types, which isn't really an issue when you're publishing your compiled dist - runtime it continues working just fine). I personally prefer peerDependencies because it allows consumers to use different versions of middy as they are released, and if they break lambda-utils by updating middy, they can always roll back (vs. having to keep lambda-utils up to date as middy is maintained).

For example, between middy 0.19 and 0.29, they've released the ability for async handlers, but the existing pattern (before/after/onError, with next() function), has not changed, even though the types have changed (which only impacted compiling the dist).

I see your point though. I didn't personally experience the breaking change with FunctionShield you did so I might be a bit more naively optimistic. Maybe there's some other solution.

**Comment by kernwig** [comment]
I see. (Although I have used async middleware already 🤔, but that's beside the point.)

A compromise should work. Lock the devDependency to "0.29.x", but peerDependency at "0.x.x".

Please update lambda-utils/package.json's `version` to `2.0.0`, since anyone using lambda-utils will have to now import middy themselves. Probably need documentation changes too? If that isn't something you are comfortable with, I can do it in a followup PR.

**Comment by russell-dot-js** [comment]
Done! Check it out

**Comment by kernwig** [comment]
🤔 This diff is still showing the changes that were just merged from #17. I don't know why Github tends to fail like this, but pulling master back into your branch @russell-dot-js should provide a proper diff and clean merge.

**Comment by russell-dot-js** [comment]
> 🤔 This diff is still showing the changes that were just merged from #17. I don't know why Github tends to fail like this, but pulling master back into your branch @russell-dot-js should provide a proper diff and clean merge.

Oof. I didn't think #17 would get merged, this was a replacement for it. Let me resolve conflicts and push

**Comment by russell-dot-js** [comment]
g2g

**Pull request merged**
