### PR TITLE
Fix doc creation outside ReadTheDocs

### PR DESCRIPTION
**Pull request by troyready**

### CODE REVIEW

**Comment by kernwig** [comment]
That basically _is_ this issue voodoCQ. This PR is trying to fix a previous PR that was trying to fix that problem.

**Comment by kernwig** [comment]
Troy, just remove `make html` from `make.sh`. I only put it in there so that make.sh can be the end-all of CICD script. If it's working against you, just remove it.

Other choice is to add a command-line option in `make.sh` to control it.

**Comment by troyready** [comment]
Sounds good -- I updated the make.sh `make html` call to be conditional instead.

**Comment by troyready** [comment]
Approved by @kernwig via email

**Pull request merged**
